title: Travel at home
author: Christin Thoma
email: your-email@domain.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  This is the new travelblog for people in Covid times. We are home and we love it.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  ChristinThoma # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
